# Generated by Django 4.1.5 on 2023-02-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_slug_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
