# Generated by Django 4.1.5 on 2023-02-20 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_itempedido_data_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='data_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
